name: Hello, World!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    env:
     USER_NAME : "hoge"
    steps:
     - run : ls -R
     - run : echo "hogehoge"
     - run : cat hoge.txt
     - run : echo hoge.txt
     - run : cat README.md
    #  - run : cat README.md
  
    #  - run : echo "secret user name : ${{secrets.USER_NAME}}"
